### ISSUE TITLE
Please tag a release

### ISSUE THREAD

**Issue by CyberShadow** [D-Programming-Deimos/libpng#5]
Currently this package is not usable from Dub due to issues fixed in master, but not yet present in a tag.

BTW, if you don't want to maintain this repository any more, it can be transferred to the Deimos organization.

**Comment by lionello** [comment]
Thanks. Didn't know whether force-tagging would be a good idea™, so I bumped libpng to the next patch level and tagged it `v1.6.17`

I'm OK to transfer this to Deimos org, by the way.

**Comment by lionello** [comment]
Seems I need to be a member before I can transfer the project? Says I don't have permission to create repositories under the org.

**Comment by CyberShadow** [comment]
> Didn't know whether force-tagging would be a good idea™,

In such cases it's probably better to bump the version number in some way that can't be confused with the upstream version. For example the OpenSSL bindings use their own version number, but specify the upstream binding version after the +: https://github.com/D-Programming-Deimos/openssl/releases

> so I bumped libpng to the next patch level and tagged it `v1.6.17`

Thanks!

> Seems I need to be a member before I can transfer the project? Says I don't have permission to create repositories under the org.

I think if you grant me admin rights on this repository, I should be able to transfer it.

**Comment by lionello** [comment]
`CyberShadow/libpng already exists`

**Comment by CyberShadow** [comment]
Yeah, that's my fork of the real `libpng` library. Where do you get that error?

I still can't access this repository's settings...

**Comment by lionello** [comment]
Got that when trying to transfer to you. Can you rename your fork?

**Comment by CyberShadow** [comment]
If I rename the fork, I won't be able to rename it back (or accidentally create/fork another repository there), as it will break the redirect that GitHub keeps around to keep clones working. We need that to keep Dub working.

What happens if you try to transfer to D-Programming-Deimos?

**Comment by lionello** [comment]
`You don’t have the permission to create repositories on D-Programming-Deimos`

**Comment by CyberShadow** [comment]
Try now?

**Comment by lionello** [comment]
Done!

**Comment by CyberShadow** [comment]
Ah, did you just fork it back?

That overwrote the redirect. If the Deimos project is updated, you'll need to remember to update your fork too. Or the URL on code.dlang.org needs to be changed, not sure if that's possible.

It wasn't necessary to fork it since you keep full rights after the move.

**Comment by lionello** [comment]
Doh. I was hoping we'd be able to change that URL.

I've changed the repo owner on code.dlang.org, hoping that should've fixed it.

**Comment by CyberShadow** [comment]
Thanks. Should be good hopefully.

**Comment by lionello** [comment]
I'll move all my dlang bindings to Deimos, OK?

**Comment by lionello** [comment]
(All from https://code.dlang.org/search?q=lionello except jwtd)

**Comment by CyberShadow** [comment]
Sure. Thanks!

**Comment by CyberShadow** [comment]
There is https://wiki.dlang.org/Deimos which attempts to define some conventions for Deimos projects, though maybe some things on that page should be instead updated to conform to what the majority of Deimos projects adopted.

**Comment by lionello** [comment]
OK, I'll have a look. I won't have much time to fix any deviations from that page though, so hopefully being part of Deimos others can help get them in order. To be honest, some of the libs might be obsolete, like `libcelt` is now Opus, etc..

**Comment by CyberShadow** [comment]
Yes, no worries.

**Comment by CyberShadow** [comment]
Hmm, Dub is not seeing the new tag yet. Can you try going to https://code.dlang.org/my_packages/libpng and clicking "Trigger manual update"?

**Comment by lionello** [comment]
worked.
